fix(bitwarden-pm): deserialize TwoFactorProviders from either numbers or strings
- deserialize TwoFactorProviders to be compatible with Bitwarden API

Motivation
=================
When adding Bitwarden SaaS account using bitwarden-pm provider, user is correctly asked for master password.
If account has any 2FA type enabled, user is presented with an error instead of 2FA prompt.
User-facing error:
Error: org.freedesktop.DBus.Error.Failed: auth_provider_with_tty error: auth failed for 'bw': org.freedesktop.DBus.Error.Failed: auth_failed

Service's journal line:
Mar 07 15:30:38 tirith rosecd[96525]: 2026-03-07T14:30:38.565812Z  WARN extism::pdk: unlock failed: authentication failed: login failed (400): {"error":"invalid_grant","error_description":"Two factor required.","TwoFactorProviders":["0","7","3"],"TwoFactorProviders2":{"0":null,"7":{"challenge":"<ANONYMIZED>","timeout":60000,"rpId":"vault.bitwarden.com","allowCredentials":[{"type":"public-key","id":"<ANONYMIZED>"}],"userVerification":"discouraged","extensions":{"appid":"https://vault.bitwarden.com/app-id.json","uvm":true},"status":"ok","errorMessage":""},"3":{"Nfc":true}},"MasterPasswordPolicy":{"Object":"masterPasswordPolicy"}} plugin="db243ebf-97a4-4111-b7e7-dac39db3a0a1"